### ISSUE TITLE
Fix projection coloring on filtered projection

### ISSUE THREAD

**Issue by cabreraalex** [zeno-ml/zeno#357]
Coloring doesn't seem to work for the filtered projection.

**Comment by xnought** [comment]
@cabreraalex Incorrectly coloring? Or not at all?

**Comment by cabreraalex** [comment]
I think incorrectly, try using the "incorrect" boolean to color

**Comment by xnought** [comment]
Just to note, as discussed, the bug occurs when switching what metadata to color by in discovery. Sometimes it doesn't color some points in the scatter 2D. Sometimes it does. Sometimes it doesn't switch. And the reprojection colors aren't right.

Since that problem is so uniform, it is a problem with the coloring assignment itself in `metadata.ts` or in the way the colors are being assigned in the `scatter` svelte file.
